education:
Students enrolled in primary education (thousands)
Gross enrollement ratio - Primary (male)
Gross enrollment ratio - Primary (female)
Students enrolled in secondary education (thousands)
Gross enrollment ratio - Secondary (male)
Gross enrollment ratio - Secondary (female)
Students enrolled in tertiary education (thousands)
Gross enrollment ratio - Tertiary (male)
Gross enrollment ratio - Tertiary (female)
Students enrolled in primary education (thousands)
Gross enrollement ratio - Primary (male)
Gross enrollment ratio - Primary (female)
Students enrolled in secondary education (thousands)
Gross enrollment ratio - Secondary (male)
Gross enrollment ratio - Secondary (female)
Students enrolled in primary education (thousands)
Gross enrollement ratio - Primary (male)
Gross enrollment ratio - Primary (female)
Students enrolled in secondary education (thousands)
Gross enrollment ratio - Secondary (male)
Gross enrollment ratio - Secondary (female)
Students enrolled in tertiary education (thousands)
Gross enrollment ratio - Tertiary (male)
Gross enrollment ratio - Tertiary (female)
Students enrolled in primary education (thousands)
Gross enrollement ratio - Primary (male)
Gross enrollment ratio - Primary (female)
Students enrolled in secondary education (thousands)
Gross enrollment ratio - Secondary (male)
Gross enrollment ratio - Secondary (female)
Students enrolled in primary education (thousands)
Gross enrollement ratio - Primary (male)
Gross enrollment ratio - Primary (female)
Students enrolled in secondary education (thousands)
Gross enrollment ratio - Secondary (male)
Gross enrollment ratio - Secondary (female)
Students enrolled in tertiary education (thousands)
Gross enrollment ratio - Tertiary (male)
Gross enrollment ratio - Tertiary (female)
Students enrolled in primary education (thousands)
Gross enrollement ratio - Primary (male)
Gross enrollment ratio - Primary (female)
Students enrolled in secondary education (thousands)
Gross enrollment ratio - Secondary (male)
Gross enrollment ratio - Secondary (female)
Students enrolled in primary education (thousands)
Gross enrollement ratio - Primary (male)
Gross enrollment ratio - Primary (female)
Students enrolled in secondary education (thousands)
Gross enrollment ratio - Secondary (male)
Gross enrollment ratio - Secondary (female)
Students enrolled in tertiary education (thousands)
Gross enrollment ratio - Tertiary (male)

Labor:
Labour force participation - Total

PopFert:
Population annual rate of increase (percent)
Total fertility rate (children per women)
Infant mortality for both sexes (per 1,000 live births)
Life expectancy at birth for both sexes (years)
Life expectancy at birth for males (years)
Life expectancy at birth for females (years)
Population annual rate of increase (percent)
Total fertility rate (children per women)
Infant mortality for both sexes (per 1,000 live births)
Life expectancy at birth for both sexes (years)
Life expectancy at birth for males (years)
Life expectancy at birth for females (years)
Population annual rate of increase (percent)
Total fertility rate (children per women)
Infant mortality for both sexes (per 1,000 live births)
Life expectancy at birth for both sexes (years)
Life expectancy at birth for males (years)
Life expectancy at birth for females (years)

water:
Safely managed drinking water sources, urban (Proportion of population with access)
Safely managed drinking water sources, rural (Proportion of population with access)
Safely managed drinking water sources, total (Proportion of population with access)
Safely managed sanitation facilities, urban (Proportion of population with access)
Safely managed sanitation facilities, rural (Proportion of population with access)
Safely managed sanitation facilities, total (Proportion of population with access)
Safely managed drinking water sources, urban (Proportion of population with access)
Safely managed drinking water sources, rural (Proportion of population with access)
Safely managed drinking water sources, total (Proportion of population with access)
Safely managed sanitation facilities, urban (Proportion of population with access)
Safely managed sanitation facilities, rural (Proportion of population with access)
Safely managed sanitation facilities, total (Proportion of population with access)
Safely managed drinking water sources, urban (Proportion of population with access)
Safely managed drinking water sources, rural (Proportion of population with access)
Safely managed drinking water sources, total (Proportion of population with access)
Safely managed sanitation facilities, urban (Proportion of population with access)
Safely managed sanitation facilities, rural (Proportion of population with access)
